; Script generated by the Inno Setup Script Wizard and customized for Eduxal.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Eduxal
AppVersion=1.0.0
DefaultDirName={autopf}\Eduxal
DefaultGroupName=Eduxal
OutputDir=build\windows\x64\runner
OutputBaseFilename=eduxal-windows-installer-x64
Compression=lzma
SolidCompression=yes
SetupIconFile=windows\runner\resources\app_icon.ico
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
DisableWelcomePage=no
DisableDirPage=no
DisableProgramGroupPage=yes

[Files]
Source: "build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs
Source: "vc_redist.x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall

[Icons]
Name: "{group}\Eduxal"; Filename: "{app}\eduxal.exe"
Name: "{autodesktop}\Eduxal"; Filename: "{app}\eduxal.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Run]
Filename: "{tmp}\vc_redist.x64.exe"; Parameters: "/quiet /norestart"; Check: VCUpdateNeeded; StatusMsg: "Installing Microsoft Visual C++ Redistributable..."
Filename: "{app}\eduxal.exe"; Description: "{cm:LaunchProgram,Eduxal}"; Flags: nowait postinstall skipifsilent

[Code]
function VCUpdateNeeded(): Boolean;
var
  InstalledValue: Cardinal;
begin
  // Default to true (need to install) if not found
  Result := True;
  if RegQueryDWordValue(HKLM64, 'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64', 'Installed', InstalledValue) then
  begin
    if InstalledValue = 1 then
    begin
      Result := False; // Already installed, skip installation
    end;
  end;
end;
