; Script generated by the Inno Setup Script Wizard and customized for Eduxal.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Eduxal
AppVersion=1.0.0
DefaultDirName={localappdata}\Programs\Eduxal
DefaultGroupName=Eduxal
OutputDir=..\build\windows\x64\runner
OutputBaseFilename=eduxal installer
Compression=lzma
SolidCompression=yes
SetupIconFile=runner\resources\app_icon.ico
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
DisableWelcomePage=yes
DisableDirPage=yes
DisableProgramGroupPage=yes
DisableReadyPage=yes
DisableFinishedPage=yes
PrivilegesRequired=lowest

[Files]
Source: "..\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs
Source: "..\vc_redist.x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall

[Icons]
Name: "{group}\Eduxal"; Filename: "{app}\eduxal.exe"
Name: "{autodesktop}\Eduxal"; Filename: "{app}\eduxal.exe"


[Run]
Filename: "{tmp}\vc_redist.x64.exe"; Parameters: "/quiet /norestart"; Check: VCUpdateNeeded; StatusMsg: "Installing Microsoft Visual C++ Redistributable..."
Filename: "{app}\eduxal.exe"; Flags: nowait runasoriginaluser

[Code]
function VCUpdateNeeded(): Boolean;
var
  InstalledValue: Cardinal;
begin
  // Default to true (need to install) if not found
  Result := True;
  if RegQueryDWordValue(HKLM64, 'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64', 'Installed', InstalledValue) then
  begin
    if InstalledValue = 1 then
    begin
      Result := False; // Already installed, skip installation
    end;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  BatchFile: String;
  BatchContent: String;
  ErrorCode: Integer;
begin
  if CurStep = ssDone then
  begin
    BatchFile := ExpandConstant('{tmp}\SelfDelete.bat');
    BatchContent := 
      ':try_delete' + #13 + #10 +
      'del "' + ExpandConstant('{srcexe}') + '"' + #13 + #10 +
      'if exist "' + ExpandConstant('{srcexe}') + '" (' + #13 + #10 +
      '  ping 127.0.0.1 -n 2 > nul' + #13 + #10 +
      '  goto try_delete' + #13 + #10 +
      ')' + #13 + #10 +
      'del "%0"';
    SaveStringToFile(BatchFile, BatchContent, False);
    Exec(BatchFile, '', '', SW_HIDE, ewNoWait, ErrorCode);
  end;
end;
