import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../../../client.dart';
import '../../../../database/daos/exams_grades_dao.dart';
import '../../../../database/database.dart';
import '../../../../database/tables/curriculum_subjects.dart';
import '../../../../models/school_config.dart';
import '../../../../models/result.dart';
import '../../../theme/app_theme.dart';
import '../../../widgets/edu_tab_bar.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Create Assignment Page
//
// Single-page form that:
//   1. Collects assignment name, topics + weights, total marks, and due date.
//   2. Calls PaperService.createPaper (eventId = '', type = 1).
//   3. Calls PaperService.generateAssignment with the returned paperId.
//   4. On success: navigates to StudentPapersListPage (TODO Task F1).
// ─────────────────────────────────────────────────────────────────────────────

class CreateAssignmentPage extends StatefulWidget {
  const CreateAssignmentPage({
    super.key,
    required this.schoolId,
    required this.subjectId,
    required this.subjectName,
    required this.grade,
    required this.curriculumType,
    this.stream,
  });

  final String schoolId;
  final int subjectId;
  final String subjectName;
  final int grade;
  final CurriculumType curriculumType;
  final int? stream;

  @override
  State<CreateAssignmentPage> createState() => _CreateAssignmentPageState();
}

class _CreateAssignmentPageState extends State<CreateAssignmentPage>
    with TickerProviderStateMixin {
  final _formKey = GlobalKey<FormState>();
  final _nameCtrl = TextEditingController();
  final _marksCtrl = TextEditingController(text: '30');

  late int _selectedGrade;
  TabController? _gradeTabController;
  List<MapEntry<int, String>> _allowedGrades = [];

  DateTime? _dueDate;
  List<({int id, String name})> _allTopics = [];
  Set<int> _selectedTopics = {};
  final Map<int, double> _weights = {};
  bool _submitting = false;
  bool _topicsLoading = true;
  bool _isNameManuallyEdited = false;
  String? _autoGeneratedName;

  Future<void> _syncAutoName() async {
    if (_isNameManuallyEdited) return;
    if (_selectedTopics.isEmpty) {
      _autoGeneratedName = null;
      setState(() {
        _nameCtrl.text = '';
      });
      return;
    }

    final selected = _allTopics.where((t) => _selectedTopics.contains(t.id)).toList();
    if (selected.isEmpty) return;

    final topicTitle = selected.map((t) => t.name).join(', ');
    final seq = await ExamsGradesDao(db).getNextTopicPaperNumber(
      schoolId: widget.schoolId,
      subject: widget.subjectId,
      grade: _selectedGrade,
      stream: widget.stream,
      topicName: selected.first.name,
      isAssessment: false,
    );
    final generated = 'Assignment $seq of $topicTitle';
    _autoGeneratedName = generated;
    setState(() {
      _nameCtrl.text = generated;
    });
  }

  // ── Lifecycle ─────────────────────────────────────────────────────────────

  @override
  void initState() {
    super.initState();
    _selectedGrade = widget.grade;
    _allowedGrades = _computeAllowedGrades();

    if (_allowedGrades.length > 1) {
      final initialIdx =
          _allowedGrades.indexWhere((e) => e.key == _selectedGrade);
      _gradeTabController = TabController(
        length: _allowedGrades.length,
        vsync: this,
        initialIndex: initialIdx >= 0 ? initialIdx : 0,
      )..addListener(() {
        if (_gradeTabController!.indexIsChanging) return;
        final newGrade = _allowedGrades[_gradeTabController!.index].key;
        if (newGrade != _selectedGrade) {
          setState(() {
            _selectedGrade = newGrade;
            // Note: unlike assessments, we might NOT want to clear selections
            // if topics are shared across grades? But usually they aren't.
            _selectedTopics.clear();
            _weights.clear();
            if (!_isNameManuallyEdited) {
              _autoGeneratedName = null;
              _nameCtrl.text = '';
            }
            _loadTopics();
          });
        }
      });
    }

    _loadTopics();
  }

  List<MapEntry<int, String>> _computeAllowedGrades() {
    final labels = gradeLabelsFor(widget.curriculumType);
    final entries = labels.entries.toList()
      ..sort((a, b) => a.key.compareTo(b.key));
    return entries;
  }

  @override
  void dispose() {
    _nameCtrl.dispose();
    _marksCtrl.dispose();
    _gradeTabController?.dispose();
    super.dispose();
  }

  // ── Data loading ──────────────────────────────────────────────────────────

  Future<void> _loadTopics() async {
    setState(() => _topicsLoading = true);
    try {
      final rows = await catalogDao
          .watchTopicsBySubjectAndGrade(
            subjectId: widget.subjectId,
            grade: _selectedGrade,
          )
          .first;
      if (!mounted) return;
      setState(() {
        _allTopics = rows.map((t) => (id: t.id, name: t.name)).toList();
        _topicsLoading = false;
      });
    } catch (e) {
      if (!mounted) return;
      setState(() => _topicsLoading = false);
    }
  }

  // ── Actions ───────────────────────────────────────────────────────────────

  Future<void> _pickDate() async {
    final now = DateTime.now();
    final picked = await showDatePicker(
      context: context,
      initialDate: _dueDate ?? now.add(const Duration(days: 7)),
      firstDate: now,
      lastDate: DateTime(now.year + 2),
    );
    if (picked != null) {
      setState(() => _dueDate = picked);
    }
  }

  Future<void> _submit() async {
    if (!(_formKey.currentState?.validate() ?? false)) return;
    if (_selectedTopics.isEmpty) {
      _showSnackBar('Please select at least one topic.');
      return;
    }
    if (_dueDate == null) {
      _showSnackBar('Please select a due date.');
      return;
    }

    setState(() => _submitting = true);

    // ── Step 1: Create paper ────────────────────────────────────────────────
    final createResult = await paperService.createPaper(
      school: widget.schoolId,
      eventId: '',
      subject: widget.subjectId,
      grade: _selectedGrade,
      stream: widget.stream ?? 0,
      type: 1,
      name: _nameCtrl.text.trim(),
      totalMarks: int.parse(_marksCtrl.text.trim()),
      durationMinutes: 0,
      date: _dueDate!,
      topicWeights: const [],
      accessToken: accessToken,
    );

    if (!mounted) return;

    switch (createResult) {
      case Err(:final error):
        _showSnackBar(
          'Failed to create assignment: ${error.message ?? error.toString()}',
        );
        setState(() => _submitting = false);
        return;

      case Ok(:final value):
        final paperId = value;

        // ── Step 2: Trigger assignment generation ───────────────────────────
        final genResult = await paperService.generateAssignment(
          paperId: paperId,
          accessToken: accessToken,
        );

        if (!mounted) return;

        switch (genResult) {
          case Err(:final error):
            _showSnackBar(
              'Generation failed: ${error.message ?? error.toString()}',
            );
            setState(() => _submitting = false);

          case Ok(:final value):
            setState(() => _submitting = false);
            if (value) {
              // TODO(Task F1): Replace stub with:
              //   Navigator.push(context, MaterialPageRoute(
              //     builder: (_) => StudentPapersListPage(
              //       paperId: paperId,
              //       paperName: _nameCtrl.text.trim(),
              //     ),
              //   ));
              _showSnackBar('Assignment generation started');
              if (mounted) Navigator.pop(context);
            } else {
              _showSnackBar('Server rejected the generation request.');
            }
        }
    }
  }

  void _showSnackBar(String message) {
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(message, style: const TextStyle(fontSize: 13))),
    );
  }

  // ── Build ─────────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    final isDark = cs.brightness == Brightness.dark;

    return Scaffold(
      backgroundColor: isDark
          ? const Color(0xFF0A0E13)
          : cs.surfaceContainerLowest,
      appBar: _buildAppBar(cs, isDark),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.fromLTRB(16, 16, 16, 40),
          children: [
            _buildFormCard(cs, isDark),
            const SizedBox(height: 24),
            _SubmitButton(
              submitting: _submitting,
              onTap: _submitting ? null : _submit,
              cs: cs,
              isDark: isDark,
            ),
          ],
        ),
      ),
    );
  }

  PreferredSizeWidget _buildAppBar(ColorScheme cs, bool isDark) {
    return AppBar(
      backgroundColor: isDark ? const Color(0xFF121A24) : cs.surface,
      elevation: 0,
      scrolledUnderElevation: 0,
      leadingWidth: 48,
      leading: IconButton(
        icon: const Icon(Icons.chevron_left_rounded, size: 24),
        tooltip: 'Back',
        onPressed: () => Navigator.of(context).pop(),
      ),
      title: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            'Create Assignment',
            style: TextStyle(
              fontSize: 15,
              fontWeight: FontWeight.w500,
              color: cs.onSurface,
            ),
          ),
          Text(
            widget.subjectName,
            style: TextStyle(
              fontSize: 12,
              fontWeight: FontWeight.w300,
              color: cs.onSurfaceVariant.withValues(alpha: 0.65),
            ),
          ),
        ],
      ),
      bottom: _gradeTabController == null
          ? null
          : EduTabBarBottom(
              controller: _gradeTabController!,
              tabs: _allowedGrades.map((e) => EduTab(label: e.value)).toList(),
              isScrollable: true,
            ),
    );
  }

  Widget _buildFormCard(ColorScheme cs, bool isDark) {
    return _Card(
      cs: cs,
      isDark: isDark,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // ── Name ──────────────────────────────────────────────────────────
          _FieldLabel(label: 'Assignment Name', cs: cs),
          const SizedBox(height: 6),
          TextFormField(
            controller: _nameCtrl,
            onChanged: (val) {
              if (val.trim().isEmpty) {
                _isNameManuallyEdited = false;
              } else if (val != _autoGeneratedName) {
                _isNameManuallyEdited = true;
              }
            },
            textInputAction: TextInputAction.next,
            autocorrect: false,
            style: TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.w400,
              color: cs.onSurface,
            ),
            decoration: _fieldDeco(
              hint: 'e.g. Assignment 1 of Topic',
              cs: cs,
              isDark: isDark,
            ),
            validator: (v) {
              if (v == null || v.trim().isEmpty) {
                return 'Assignment name is required';
              }
              return null;
            },
          ),

          const SizedBox(height: 20),

          _FieldLabel(label: 'Select Topics', cs: cs),
          const SizedBox(height: 8),

          if (_topicsLoading)
            const Padding(
              padding: EdgeInsets.symmetric(vertical: 20),
              child: Center(
                child: SizedBox(
                  width: 20,
                  height: 20,
                  child: CircularProgressIndicator(strokeWidth: 2),
                ),
              ),
            )
          else if (_allTopics.isEmpty)
            Padding(
              padding: const EdgeInsets.symmetric(vertical: 8),
              child: Text(
                'No topics available for this subject and grade.',
                style: TextStyle(
                  fontSize: 13,
                  fontWeight: FontWeight.w300,
                  color: cs.onSurfaceVariant.withValues(alpha: 0.55),
                ),
              ),
            )
          else
            Wrap(
              spacing: 6,
              runSpacing: 6,
              children: _allTopics.map((topic) {
                final selected = _selectedTopics.contains(topic.id);
                return FilterChip(
                  label: Text(
                    topic.name,
                    style: TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.w400,
                      color: selected ? cs.onPrimary : cs.onSurface,
                    ),
                  ),
                  selected: selected,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(AppTheme.kChipRadius),
                    side: BorderSide(
                      color: selected
                          ? cs.primary
                          : AppTheme.borderColor(isDark, cs),
                    ),
                  ),
                  backgroundColor: isDark
                      ? const Color(0xFF1A2435)
                      : cs.surfaceContainerHighest,
                  selectedColor: cs.primary,
                  checkmarkColor: cs.onPrimary,
                  showCheckmark: false,
                  padding: const EdgeInsets.symmetric(
                    horizontal: 8,
                    vertical: 4,
                  ),
                  onSelected: (val) {
                    setState(() {
                      if (val) {
                        _selectedTopics = {..._selectedTopics, topic.id};
                        _weights.putIfAbsent(topic.id, () => 1.0);
                      } else {
                        _selectedTopics = _selectedTopics
                            .where((id) => id != topic.id)
                            .toSet();
                        _weights.remove(topic.id);
                      }
                    });
                    _syncAutoName();
                  },
                );
              }).toList(),
            ),

          // ── Selected topics with weight sliders ───────────────────────────
          if (_selectedTopics.isNotEmpty) ...[
            const SizedBox(height: 16),
            _FieldLabel(label: 'Topic Weights', cs: cs),
            const SizedBox(height: 6),
            Container(
              decoration: BoxDecoration(
                color: isDark
                    ? const Color(0xFF1A2435)
                    : cs.surfaceContainerHighest,
                borderRadius: BorderRadius.circular(AppTheme.kCardRadius),
                border: Border.all(color: AppTheme.borderColor(isDark, cs)),
              ),
              child: Column(
                children: () {
                  final selectedList = _allTopics
                      .where((t) => _selectedTopics.contains(t.id))
                      .toList();
                  return selectedList.asMap().entries.map((entry) {
                    final index = entry.key;
                    final topic = entry.value;
                    final weight = _weights[topic.id] ?? 1.0;
                    final isLast = index == selectedList.length - 1;
                    return Column(
                      children: [
                        Padding(
                          padding: const EdgeInsets.fromLTRB(12, 8, 8, 6),
                          child: Row(
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Expanded(
                                flex: 3,
                                child: Text(
                                  topic.name,
                                  style: TextStyle(
                                    fontSize: 13,
                                    fontWeight: FontWeight.w400,
                                    color: cs.onSurface,
                                  ),
                                  maxLines: 2,
                                  overflow: TextOverflow.ellipsis,
                                ),
                              ),
                              Expanded(
                                flex: 4,
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.end,
                                  mainAxisSize: MainAxisSize.min,
                                  children: [
                                    Text(
                                      '${weight.toStringAsFixed(1)}\u00d7',
                                      style: TextStyle(
                                        fontSize: 11,
                                        fontWeight: FontWeight.w500,
                                        color: cs.primary,
                                      ),
                                    ),
                                    SliderTheme(
                                      data: SliderThemeData(
                                        trackHeight: 2,
                                        thumbShape: const RoundSliderThumbShape(
                                          enabledThumbRadius: 7,
                                        ),
                                        overlayShape:
                                            const RoundSliderOverlayShape(
                                              overlayRadius: 14,
                                            ),
                                        activeTrackColor: cs.primary,
                                        inactiveTrackColor: cs.primary
                                            .withValues(alpha: 0.18),
                                        thumbColor: cs.primary,
                                        overlayColor: cs.primary.withValues(
                                          alpha: 0.12,
                                        ),
                                      ),
                                      child: Slider(
                                        value: weight,
                                        min: 0.5,
                                        max: 3.0,
                                        divisions: 5,
                                        label:
                                            '${weight.toStringAsFixed(1)}\u00d7',
                                        onChanged: (v) {
                                          setState(
                                            () => _weights[topic.id] = v,
                                          );
                                        },
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                        if (!isLast)
                          Divider(
                            height: 1,
                            thickness: 0.5,
                            color: AppTheme.borderColor(isDark, cs),
                          ),
                      ],
                    );
                  }).toList();
                }(),
              ),
            ),
          ],

          const SizedBox(height: 20),

          // ── Total marks ───────────────────────────────────────────────────
          _FieldLabel(label: 'Total Marks', cs: cs),
          const SizedBox(height: 6),
          TextFormField(
            controller: _marksCtrl,
            keyboardType: TextInputType.number,
            textInputAction: TextInputAction.done,
            inputFormatters: [FilteringTextInputFormatter.digitsOnly],
            style: TextStyle(
              fontSize: 14,
              fontWeight: FontWeight.w400,
              color: cs.onSurface,
            ),
            decoration: _fieldDeco(hint: 'e.g. 30', cs: cs, isDark: isDark),
            validator: (v) {
              if (v == null || v.trim().isEmpty) {
                return 'Total marks is required';
              }
              final n = int.tryParse(v.trim());
              if (n == null || n <= 0) {
                return 'Enter a positive integer';
              }
              return null;
            },
          ),

          const SizedBox(height: 20),

          // ── Due date ──────────────────────────────────────────────────────
          _FieldLabel(label: 'Due Date', cs: cs),
          const SizedBox(height: 6),
          _DateTile(
            selectedDate: _dueDate,
            cs: cs,
            isDark: isDark,
            onTap: _pickDate,
          ),
        ],
      ),
    );
  }

  InputDecoration _fieldDeco({
    required String hint,
    required ColorScheme cs,
    required bool isDark,
  }) {
    final fillColor = isDark
        ? const Color(0xFF1A2435)
        : cs.surfaceContainerHighest;
    final border = OutlineInputBorder(
      borderRadius: BorderRadius.circular(AppTheme.kCardRadius),
      borderSide: BorderSide(color: AppTheme.borderColor(isDark, cs)),
    );
    return InputDecoration(
      hintText: hint,
      hintStyle: TextStyle(
        fontSize: 13,
        fontWeight: FontWeight.w300,
        color: cs.onSurfaceVariant.withValues(alpha: 0.5),
      ),
      contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 11),
      filled: true,
      fillColor: fillColor,
      border: border,
      enabledBorder: border,
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppTheme.kCardRadius),
        borderSide: BorderSide(color: cs.primary, width: 1.5),
      ),
      errorBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppTheme.kCardRadius),
        borderSide: BorderSide(color: cs.error),
      ),
      focusedErrorBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(AppTheme.kCardRadius),
        borderSide: BorderSide(color: cs.error, width: 1.5),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Date tile — tappable row that opens a date picker
// ─────────────────────────────────────────────────────────────────────────────

class _DateTile extends StatelessWidget {
  const _DateTile({
    required this.selectedDate,
    required this.cs,
    required this.isDark,
    required this.onTap,
  });

  final DateTime? selectedDate;
  final ColorScheme cs;
  final bool isDark;
  final VoidCallback onTap;

  String get _label {
    if (selectedDate == null) return 'Tap to select a due date';
    final d = selectedDate!;
    const months = [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ];
    return '${d.day} ${months[d.month - 1]} ${d.year}';
  }

  @override
  Widget build(BuildContext context) {
    final hasDate = selectedDate != null;
    final fillColor = isDark
        ? const Color(0xFF1A2435)
        : cs.surfaceContainerHighest;
    final borderCol = AppTheme.borderColor(isDark, cs);

    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(AppTheme.kCardRadius),
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 11),
        decoration: BoxDecoration(
          color: fillColor,
          borderRadius: BorderRadius.circular(AppTheme.kCardRadius),
          border: Border.all(color: borderCol),
        ),
        child: Row(
          children: [
            Icon(
              Icons.calendar_today_rounded,
              size: 15,
              color: hasDate
                  ? cs.primary.withValues(alpha: 0.85)
                  : cs.onSurfaceVariant.withValues(alpha: 0.5),
            ),
            const SizedBox(width: 10),
            Text(
              _label,
              style: TextStyle(
                fontSize: 13,
                fontWeight: hasDate ? FontWeight.w400 : FontWeight.w300,
                color: hasDate
                    ? cs.onSurface
                    : cs.onSurfaceVariant.withValues(alpha: 0.5),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Submit button with animated press + loading state
// ─────────────────────────────────────────────────────────────────────────────

class _SubmitButton extends StatefulWidget {
  const _SubmitButton({
    required this.submitting,
    required this.onTap,
    required this.cs,
    required this.isDark,
  });

  final bool submitting;
  final VoidCallback? onTap;
  final ColorScheme cs;
  // ignore: unused_field
  final bool isDark;

  @override
  State<_SubmitButton> createState() => _SubmitButtonState();
}

class _SubmitButtonState extends State<_SubmitButton>
    with SingleTickerProviderStateMixin {
  late final AnimationController _scaleCtrl;
  late final Animation<double> _scale;

  @override
  void initState() {
    super.initState();
    _scaleCtrl = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 80),
      reverseDuration: const Duration(milliseconds: 120),
      lowerBound: 0.0,
      upperBound: 1.0,
      value: 1.0,
    );
    _scale = Tween<double>(
      begin: 0.97,
      end: 1.0,
    ).animate(CurvedAnimation(parent: _scaleCtrl, curve: Curves.easeOut));
  }

  @override
  void dispose() {
    _scaleCtrl.dispose();
    super.dispose();
  }

  void _onTapDown(TapDownDetails _) => _scaleCtrl.reverse();
  void _onTapUp(TapUpDetails _) => _scaleCtrl.forward();
  void _onTapCancel() => _scaleCtrl.forward();

  @override
  Widget build(BuildContext context) {
    final cs = widget.cs;
    final disabled = widget.onTap == null;

    return GestureDetector(
      onTapDown: disabled ? null : _onTapDown,
      onTapUp: disabled ? null : _onTapUp,
      onTapCancel: disabled ? null : _onTapCancel,
      onTap: widget.onTap,
      child: ScaleTransition(
        scale: _scale,
        child: Container(
          height: 48,
          decoration: BoxDecoration(
            color: disabled ? cs.primary.withValues(alpha: 0.4) : cs.primary,
            borderRadius: BorderRadius.circular(AppTheme.kCardRadius),
          ),
          alignment: Alignment.center,
          child: widget.submitting
              ? SizedBox(
                  width: 18,
                  height: 18,
                  child: CircularProgressIndicator(
                    strokeWidth: 1.5,
                    valueColor: AlwaysStoppedAnimation<Color>(
                      cs.onPrimary.withValues(alpha: 0.85),
                    ),
                  ),
                )
              : Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Icon(
                      Icons.assignment_rounded,
                      size: 16,
                      color: cs.onPrimary,
                    ),
                    const SizedBox(width: 8),
                    Text(
                      'Generate Assignments',
                      style: TextStyle(
                        fontSize: 14,
                        fontWeight: FontWeight.w500,
                        color: cs.onPrimary,
                        letterSpacing: 0.2,
                      ),
                    ),
                  ],
                ),
        ),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Shared helpers
// ─────────────────────────────────────────────────────────────────────────────

class _Card extends StatelessWidget {
  const _Card({required this.cs, required this.isDark, required this.child});

  final ColorScheme cs;
  final bool isDark;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: isDark ? const Color(0xFF121A24) : cs.surface,
        borderRadius: BorderRadius.circular(AppTheme.kCardRadius),
        border: Border.all(color: AppTheme.borderColor(isDark, cs)),
      ),
      child: child,
    );
  }
}

class _FieldLabel extends StatelessWidget {
  const _FieldLabel({required this.label, required this.cs});

  final String label;
  final ColorScheme cs;

  @override
  Widget build(BuildContext context) {
    return Text(
      label,
      style: TextStyle(
        fontSize: 12,
        fontWeight: FontWeight.w500,
        color: cs.onSurfaceVariant.withValues(alpha: 0.8),
        letterSpacing: 0.1,
      ),
    );
  }
}
